dribdat/__init__.py
"""Main application package."""

dribdat/admin/__init__.py
# -*- coding: utf-8 -*-

from . import views

dribdat/admin/views.py
# -*- coding: utf-8 -*-

from flask import (
    Blueprint, render_template, redirect, url_for,
    request, flash, jsonify
)
from flask_login import login_required

from ..utils import sanitize_input, get_time_note, get_random_alphanumeric_string
from ..extensions import db, cache
from ..decorators import admin_required
from ..aggregation import GetProjectData, SyncProjectData
from ..user.models import Role, User, Event, Activity, Project, Category
from ..public.userhelper import get_user_by_name
from .forms import (
    RoleForm, CategoryForm,
    EventForm, ProjectForm,
    UserForm, UserProfileForm,
)

from datetime import datetime
from dribdat.futures import UTC



blueprint = Blueprint('admin', __name__, url_prefix='/admin')


@blueprint.route('/')
@login_required
@admin_required
def index():
    current_event = Event.query.filter_by(is_current=True).first()
    if current_event is None:
        sum_hidden = 0
    else:
        sum_hidden = Project.query.filter(Project.event_id==current_event.id) \
                                  .filter(Project.is_hidden).count()
    stats = [
        {
            'value': Event.query.count(),
            'text': 'Events',
            'icon': 'calendar',
            'height': 10
        }, {
            'value': User.query.count(),
            'text': 'Users',
            'icon': 'user',
            'height': 11
        }, {
            'value': Project.query.filter(Project.progress == 0).count(),
            'text': 'Challenges',
            'icon': 'trophy',
            'height': 13
        }, {
            'value': Project.query.filter(Project.progress > 0).count(),
            'text': 'Projects',
            'icon': 'star',
            'height': 16
        }, {
            'value': Activity.query.count(),
            'text': 'Dribs',
            'icon': 'comments',
            'height': 16
        },
    ]
    if sum_hidden > 0:
        flash(('There are %d projects in the featured event ' % sum_hidden) + \
              ' that are hidden and may need moderation.', 'secondary')
    return render_template('admin/index.html',
                           stats=stats, timeinfo=get_time_note(),
                           default_event=current_event, active='index')


@blueprint.route('/users')
@blueprint.route('/users/pp/<int:page>')
@login_required
@admin_required
def users(page=1):
    sort_by = request.args.get('sort')
    if sort_by == 'id':
        users = User.query.order_by(
            User.id.asc()
        )
    elif sort_by == 'admin':
        users = User.query.order_by(
            User.is_admin.desc()
        )
    elif sort_by == 'sso':
        users = User.query.order_by(
            User.sso_id.desc()
        )
    elif sort_by == 'updated':
        users = User.query.order_by(
            User.updated_at.desc()
        )
    elif sort_by == 'email':
        users = User.query.order_by(
            User.email.asc()
        )
    elif sort_by == 'username':
        users = User.query.order_by(
            User.username.asc()
        )
    else:  # Default: created
        sort_by = 'created'
        users = User.query.order_by(
            User.created_at.desc()
        )
    search_by = request.args.get('search')
    if search_by and len(search_by) > 1:
        q = "%%%s%%" % search_by.lower()
        if '@' in search_by:
            users = users.filter(User.email.ilike(q))
        else:
            users = users.filter(User.username.ilike(q))
    userpages = users.paginate(page=page, per_page=20)
    return render_template('admin/users.html', sort_by=sort_by,
                           data=userpages, endpoint='admin.users', active='users')


@blueprint.route('/user/<int:user_id>', methods=['GET', 'POST'])
@login_required
@admin_required
def user(user_id):
    user = User.query.filter_by(id=user_id).first_or_404()
    form = UserForm(obj=user, next=request.args.get('next'))
    if form.is_submitted() and form.validate():
        originalhash = user.password
        user.username = sanitize_input(form.username.data)

        # Check unique email (why does this sometimes pass validation?)
        if form.email.data != user.email:
            if User.query.filter_by(email=form.email.data).count() > 0:
                flash('A user with this e-mail already exists.', 'warning')
                return render_template('admin/useredit.html', user=user, form=form)

        del form.id
        del form.username
        form.populate_obj(user)

        # Update password if changed
        if form.password.data:
            user.set_password(form.password.data)
        else:
            user.password = originalhash

        user.updated_at = datetime.now(UTC)
        db.session.add(user)
        db.session.commit()
        user.socialize()

        flash('User updated.', 'success')
        return redirect(url_for("admin.users"))

    return render_template('admin/useredit.html', user=user, form=form)


@blueprint.route('/user/<int:user_id>/profile', methods=['GET', 'POST'])
@login_required
@admin_required
def user_profile(user_id):
    user = User.query.filter_by(id=user_id).first_or_404()
    form = UserProfileForm(obj=user, next=request.args.get('next'))
    form.roles.choices = [(r.id, r.name) for r in Role.query.order_by('name')]
    if form.is_submitted() and form.validate():
        del form.id
        # Assign roles
        user.roles = [Role.query.filter_by(
            id=r).first() for r in form.roles.data]
        del form.roles
        form.populate_obj(user)
        user.updated_at = datetime.now(UTC)
        db.session.add(user)
        db.session.commit()
        user.socialize()

        flash('User updated.', 'success')
        return redirect(url_for("admin.user", user_id=user_id))

    if not form.roles.choices:
        del form.roles
    else:
        form.roles.data = [(r.id) for r in user.roles]
    return render_template('admin/userprofile.html', user=user, form=form)


@blueprint.route('/user/new', methods=['GET', 'POST'])
@login_required
@admin_required
def user_new():
    user = User()
    user.active = True
    form = UserForm(obj=user, next=request.args.get('next'))
    del form.active
    if form.is_submitted() and form.validate():
        del form.id
        user.username = sanitize_input(form.username.data)
        if User.query.filter_by(email=form.email.data).first():
            flash('E-mail must be unique.', 'danger')
        else:
            del form.username
            form.populate_obj(user)
            if form.password.data:
                user.set_password(form.password.data)
            else:
                user.set_password(get_random_alphanumeric_string())
            db.session.add(user)
            db.session.commit()

            flash('User added.', 'success')
            return redirect(url_for("admin.users"))

    return render_template('admin/usernew.html', form=form)


@blueprint.route('/user/<int:user_id>/delete', methods=['GET', 'POST'])
@login_required
@admin_required
def user_delete(user_id):
    user = User.query.filter_by(id=user_id).first_or_404()
    if user.is_admin or user.active:
        flash('Admins and active users may not be deleted.', 'warning')
    elif len(user.projects) > 0:
        pl = ", ".join([str(i.name) for i in user.projects])
        flash('No users owning projects (%s) may be deleted.' % pl, 'warning')
    else:
        user.delete()
        flash('User deleted.', 'success')
    return redirect(url_for("admin.users"))


@blueprint.route('/user/<int:user_id>/reset/')
@login_required
@admin_required
def user_reset(user_id):
    """Reset user password."""
    user = User.query.filter_by(id=user_id).first_or_404()
    newpw = get_random_alphanumeric_string()
    user.set_password(newpw)
    db.session.add(user)
    db.session.commit()
    return render_template('admin/reset.html', newpw=newpw, email=user.email)


@blueprint.route('/user/<int:user_id>/deactivate/')
@login_required
@admin_required
def user_deactivate(user_id, reactivate=False):
    """Manage activation of user account."""
    user = User.query.filter_by(id=user_id).first_or_404()
    user.active = reactivate
    db.session.add(user)
    db.session.commit()
    if reactivate:
        flash('User %s is now active.' % user.username, 'success')
    else:
        flash('User %s deactivated.' % user.username, 'warning')
    return redirect(url_for("admin.users"))


@blueprint.route('/user/<int:user_id>/reactivate/')
@login_required
@admin_required
def user_reactivate(user_id):
    """Reactivate user account."""
    return user_deactivate(user_id, True)


@blueprint.route('/user/<int:user_id>/clearsso/')
@login_required
@admin_required
def user_clearsso(user_id):
    """Clear SSO from a user account."""
    user = User.query.filter_by(id=user_id).first_or_404()
    user.sso_id = None
    db.session.add(user)
    db.session.commit()
    flash('SSO for %s deactivated.' % user.username, 'warning')
    return redirect(url_for("admin.users"))

##############
##############
##############


@blueprint.route('/events')
@login_required
@admin_required
def events():
    events = Event.query.order_by(Event.starts_at.desc()).all()
    return render_template('admin/events.html', events=events, active='events')


@blueprint.route('/event/<int:event_id>', methods=['GET', 'POST'])
@login_required
@admin_required
def event(event_id):
    event = Event.query.filter_by(id=event_id).first_or_404()

    if event.location_lat is None or event.location_lon is None:
        event.location_lat = event.location_lon = 0

    form = EventForm(obj=event, next=request.args.get('next'))

    if form.is_submitted() and form.validate():
        form.populate_obj(event)
        event.starts_at = datetime.combine(
            form.starts_date.data, form.starts_time.data)
        event.ends_at = datetime.combine(
            form.ends_date.data, form.ends_time.data)
        event.user = get_user_by_name(form.user_name.data)

        db.session.add(event)

dribdat/app.py
# -*- coding: utf-8 -*-
"""The app module, containing the app factory function."""

from flask import Flask, render_template
from flask_cors import CORS
from flask_misaka import Misaka
from flask_mailman import Mail
from flask_talisman import Talisman
from werkzeug.middleware.proxy_fix import ProxyFix
from micawber.providers import bootstrap_basic
from whitenoise import WhiteNoise
from datetime import datetime
from urllib.parse import quote_plus
from dribdat import commands, public, admin
from dribdat.assets import assets  # noqa: I005
from dribdat.sso import get_auth_blueprint
from dribdat.extensions import (
    hashing,
    cache,
    db,
    login_manager,
    migrate,
)
from dribdat.settings import ProdConfig  # noqa: I005
from dribdat.utils import timesince
from dribdat.onebox import make_oembedplus
from pytz import timezone


def init_app(config_object=ProdConfig):
    """Define an application factory.

    See: http://flask.pocoo.org/docs/patterns/appfactories/

    :param config_object: The configuration object to use.
    """
    app = Flask(__name__)
    app.config.from_object(config_object)

    # Set up cross-site access to the API
    if app.config['SERVER_CORS']:
        CORS(app, resources={r"/api/*": {"origins": "*"}})
        app.config['CORS_HEADERS'] = 'Content-Type'

    # Set up using an external proxy/static server
    if app.config['SERVER_PROXY']:
        app.wsgi_app = ProxyFix(app, x_for=1, x_proto=1, x_host=1)
    else:
        # Internally optimize static file hosting
        app.wsgi_app = WhiteNoise(app.wsgi_app, prefix='static/')
        for static in ('css', 'img', 'js', 'public'):
            app.wsgi_app.add_files('dribdat/static/' + static)

    register_extensions(app)
    register_blueprints(app)
    register_oauthhandlers(app)
    register_errorhandlers(app)
    register_filters(app)
    register_loggers(app)
    register_shellcontext(app)
    register_commands(app)
    register_caching(app)
    return app


def register_extensions(app):
    """Register Flask extensions."""
    assets.init_app(app)
    hashing.init_app(app)
    cache.init_app(app)
    db.init_app(app)
    login_manager.init_app(app)
    migrate.init_app(app, db)
    init_mailman(app)
    init_talisman(app)
    return None


def init_mailman(app):
    """Initialize mailer support."""
    if 'MAIL_SERVER' in app.config and app.config['MAIL_SERVER']:
        if not app.config['MAIL_DEFAULT_SENDER']:
            app.logger.warn('MAIL_DEFAULT_SENDER is required to send email')
        else:
            mail = Mail()
            mail.init_app(app)


def init_talisman(app):
    """Initialize Talisman support."""
    if 'SERVER_SSL' in app.config and app.config['SERVER_SSL']:
        Talisman(app,
                 content_security_policy=app.config['CSP_DIRECTIVES'],
                 frame_options_allow_from='*')


def register_blueprints(app):
    """Register Flask blueprints."""
    app.register_blueprint(public.api.blueprint)
    app.register_blueprint(public.auth.blueprint)
    app.register_blueprint(public.views.blueprint)
    app.register_blueprint(public.feeds.blueprint)
    app.register_blueprint(public.project.blueprint)
    app.register_blueprint(admin.views.blueprint)
    return None


def register_oauthhandlers(app):
    """Set up OAuth handlers based on configuration."""
    blueprint = get_auth_blueprint(app)
    if blueprint is not None:
        app.register_blueprint(blueprint, url_prefix="/oauth")


def register_errorhandlers(app):
    """Register error handlers."""
    def render_error(error):
        """Render error template."""
        # If a HTTPException, pull the `code` attribute; default to 500
        error_code = getattr(error, 'code', 500)
        return render_template('{0}.html'.format(error_code)), error_code
    for errcode in [401, 404, 500]:
        app.errorhandler(errcode)(render_error)
    return None


def register_shellcontext(app):
    """Register shell context objects."""
    def shell_context():
        """Shell context objects."""
        from dribdat.user.models import User
        return {
            'db': db,
            'User': User}

    app.shell_context_processor(shell_context)


def register_commands(app):
    """Register Click commands."""
    app.cli.add_command(commands.lint)
    app.cli.add_command(commands.clean)
    app.cli.add_command(commands.urls)


def register_filters(app):
    """Register filters for templates."""
    #
    # Conversion of Markdown to HTML
    Misaka(app, autolink=True, fenced_code=True,
           strikethrough=True, tables=True)

    # Registration of handlers for micawber
    app.oembed_providers = bootstrap_basic()

    @app.template_filter()
    def onebox(value):
        return make_oembedplus(
            value, app.oembed_providers, maxwidth=600, maxheight=400
        )

    # Timezone helper
    app.tz = timezone(app.config['TIME_ZONE'] or 'UTC')

    # Lambda filters for safe image_url's
    app.jinja_env.filters['quote_plus'] = lambda u: quote_plus(u or '', ':/?&=')

    # Custom filters
    @app.template_filter()
    def since_date(value):
        return timesince(value)

    @app.template_filter()
    def until_date(value):
        return timesince(value, default="now!", until=True)

    @app.template_filter()
    def format_date(value, format='%d.%m.%Y'):
        if value is None: return ''
        return value.strftime(format)

    @app.template_filter()
    def format_datetime(value, format='%d.%m.%Y %H:%M'):
        if value is None: return ''
        return value.strftime(format)


def register_loggers(app):
    """Initialize and configure logging."""
    if 'DEBUG' in app.config and not app.config['DEBUG']:
        import logging
        stream_handler = logging.StreamHandler()
        app.logger.addHandler(stream_handler)
        app.logger.setLevel(logging.INFO)


def register_caching(app):
    """Prevent cached responses in debug."""
    if 'DEBUG' in app.config and app.config['DEBUG']:
        @app.after_request
        def after_request(response):
            response.headers["Cache-Control"] = "no-cache, no-store, must-revalidate, public, max-age=0"
            response.headers["Expires"] = 0
            response.headers["Pragma"] = "no-cache"
            return response

dribdat/boxout/__init__.py
# -*- coding: utf-8 -*-
"""Boxout modules for parsing resource types."""

dribdat/sso/__init__.py
"""Single Sign-On extensions."""

from .ssoutils import get_auth_blueprint

dribdat/user/__init__.py
# -*- coding: utf-8 -*-
"""The user module."""
from . import validators  # noqa

from .constants import (
    USER_ROLE, ADMIN, USER, USER_STATUS, ACTIVE,
    isUserActive,
    getProjectStages,
    validateProjectData,
    projectProgressList,
    stageProjectToNext,
)

dribdat/templates/includes/analytics.html
{% if config.ANALYTICS_FATHOM %}
<!-- Fathom - beautiful, simple website analytics -->
<script src="https://cdn.usefathom.com/script.js" site="{{ config.ANALYTICS_FATHOM }}" async defer></script>
{% endif %}

{% if config.ANALYTICS_SIMPLE %}
<!-- Simple Analytics - Simple, clean, privacy-friendly analytics -->
<script async defer src="https://scripts.simpleanalyticscdn.com/latest.js"></script>
<noscript><img src="https://queue.simpleanalyticscdn.com/noscript.gif" alt=""
/></noscript>
{% endif %}

{% if config.ANALYTICS_GOOGLE %}
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id={{ config.ANALYTICS_GOOGLE }}"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());
  gtag('config', '{{ config.ANALYTICS_GOOGLE }}');
</script>
<!-- / Google Analytics -->
{% endif %}

dribdat/templates/includes/eventhome.html
<div class="event-header">
  {% if event.logo_url and not event.gallery_url %}
    <div class="section-header-logo">
      <img id="event-logo" src="{{ event.logo_url }}" alt="Logo" title="{{ event.hostname }}" />
    </div>
  {% endif %}
  <a href="{{ url_for('public.event', event_id=event.id) }}">
    <div class="section-header-content">
      <h2 class="event-name">
        <span>{{ event.name }}</span>
      </h2>

      {% if not event.lock_resources %}
        <p class="an-event-meta">
          <span>{{ event.date }}</span>
          {% if event.hostname %}
            <i class="fa fa-bank"></i>
            <span>{{ event.hostname }}</span>
          {% endif %}
          {% if event.location %}
            <i class="fa fa-map"></i>
            <span>{{ event.location }}</span>
          {% endif %}
        </p>
      {% endif %}

      {% if event.summary|trim %}
        <div class="home-description">
          <p>{{ event.summary }}</p>
        </div>
      {% elif event.project_count %}
        <div class="embed-view">
          {{ render_embed_event(event, event.projects, False) }}
        </div>
      {% endif %}
      <div class="an-event-actions text-center mt-2">
        {% if event.project_count %}
          <a href="{{ url_for('public.event', event_id=event.id) }}" class="btn btn-info btn-lg">
          {% if event.has_finished %}
            <span>{{ event.project_count }}</span>
            <i class="fa fa-star" aria-hidden="true"></i>
            Results
          {% elif event.has_started %}
            <span>{{ event.project_count }}</span>
            <i class="fa fa-cube" aria-hidden="true"></i>
            Challenges
          {% else %}
            <span>{{ event.project_count }}</span>
            <i class="fa fa-arrow-right" aria-hidden="true"></i>
            Projects
          {% endif %}
          </a>
        {% elif event.can_start_project %}
          <a href="{{ url_for('project.project_new', event_id=event.id) }}"
             title="Write a challenge statement"
             class="btn btn-success btn-lg">
            <i class="fa fa-plus"></i>
            Challenge
          </a>
        {% endif %}

        {% if not event.has_finished %}
            {% if event.webpage_url %}
            <a href="{{ event.webpage_url }}"
                title="Visit this page for more information and to sign up"
                class="btn btn-dark btn-lg" target="_blank">
                <i class="fa fa-ticket" aria-hidden="true"></i>
                Register
            </a>
            {% endif %}
        {% endif %}
      </div><!-- /.an-event-actions -->
    </div><!-- /.header-content -->
  </a>

</div><!-- /.event-header -->

dribdat/templates/includes/footer.html
<footer id="footer">
  <a class="dribdat-logo" href="{{ url_for('public.home') }}" title="GO HOME">
    <img src="{{ url_for('static', filename='img/logo/logo13.png') }}">
  </a>

  <a href="{{ url_for('public.about') }}" class="ml-3">
    <i class="fa fa-question ml-3" aria-hidden="true"></i>
    About
  </a>

  <a href="{{ url_for('public.terms') }}">
    <i class="fa fa-exclamation ml-3" aria-hidden="true"></i>
    Terms
  </a>

  <ul class="footer-nav">
    {% if current_user and current_user.is_authenticated %}
      {% if current_user.is_admin %}
        <li>
          <a href="{{ url_for('admin.index') }}">
            <i class="fa fa-gear" aria-hidden="true"></i>
            Admin
          </a>
        </li>
      {% endif %}
      <li>
        <a href="{{ url_for('public.user_profile', username=current_user.username) }}" title="{{ current_user.username }}">
          <i class="fa fa-user" aria-hidden="true"></i>
          Profile
        </a>
      </li>
      <li>
        <a href="{{ url_for('auth.logout') }}">
          <i class="fa fa-sign-out" aria-hidden="true"></i>
          Logout
        </a>
      </li>
    {% else %}
      <li>
        <a href="{{ url_for('auth.login') }}">
          <i class="fa fa-sign-in" aria-hidden="true"></i>
          Login
        </a>
      </li>
    {% endif %}
    {% if config.ANALYTICS_HREF %}
    <li>
      <a href="{{ config.ANALYTICS_HREF }}">&#128200;&nbsp;Analytics</a>
    </li>
    {% endif %}


    <li>
        <a href="#top" id="notification-button" class="hidden ml-3">
            <i class="fa fa-bell" aria-hidden="true"></i>
            Alerts
        </a>
    </li>

    <li>
      <a class="darkmode" href="#">&#127763;&nbsp;<span>Dark</span></a>
    </li>
  </ul>
</footer>

dribdat/templates/includes/nav.html
<nav class="navbar navbar-expand-lg navbar-light bg-faded" role="navigation">

  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbar-main-collapse" aria-controls="navbar-main-collapse" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <a class="navbar-brand" href="{{ url_for('public.home') }}" title="GO HOME">
      <i style="-moz-transform: scale(1, 1); -webkit-transform: scale(1, 1); -o-transform: scale(1, 1); -ms-transform: scale(1, 1); transform: scale(1, 1);" class="fa fa-thumbs-up" aria-hidden="true"></i>
      <i style="-moz-transform: scale(1, 1); -webkit-transform: scale(1, 1); -o-transform: scale(1, 1); -ms-transform: scale(1, 1); transform: scale(1, 1);" class="fa fa-lightbulb-o" aria-hidden="true"></i>
      <i style="-moz-transform: scale(-1, 1); -webkit-transform: scale(-1, 1); -o-transform: scale(-1, 1); -ms-transform: scale(-1, 1); transform: scale(-1, 1);" class="fa fa-thumbs-up" aria-hidden="true"></i>
    </a>
  </div>

  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse" id="navbar-main-collapse">
    <ul class="navbar-nav navbar-left mr-auto nav-fill">

      {% if tabs %}
        {% for tab, link in tabs %}
        <li class="nav-item">
          <a class="nav-link {% if active == tab %}active{% endif %}" href="{{ link }}">{{ tab|capitalize }}</a>
        </li>
        {% endfor %}
      {% endif %}

      <li class="nav-item">
        <a class="nav-link {% if active == 'dribs' %}active{% endif %}"
           title="Latest posts from the teams"
           href="{{ url_for('public.dribs') }}">
          <i class="fa fa-comment bg-warning text-white" aria-hidden="true"></i>
          Dribdat
        </a>
      </li>

      {% if current_user and current_user.is_authenticated %}
          <li class="nav-item">
            <a id="project-post"
               class="nav-link{{ ' active' if active == 'post' }}"
               href="{{ url_for('public.user_post') }}"
               title="Post an update to your current project">
              <i class="fa fa-clock-o bg-info text-white" aria-hidden="true"></i>
              Post
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link{{ ' active' if active == 'profile' }}"
               title="Take me to my profile"
               href="{{ url_for('public.user_current') }}" title="My User Profile">
              <i class="fa fa-user bg-primary text-white" aria-hidden="true"></i>
              Profile
            </a>
          </li>
          {% if current_user.is_admin %}
            <li class="nav-item admin-area">
              <a class="nav-link{{ ' active' if active == 'index' }}"
                 title="The engine room"
                 href="{{ url_for('admin.index') }}">
                <i class="fa fa-gear bg-danger text-white" aria-hidden="true"></i>
                Admin
              </a>
            </li>
            {% if event %}
              <li class="nav-item">
                <a href="{{ url_for('admin.event_projects', event_id=current_event.id) }}"
                    title="Administer event projects" class="nav-link">
                  <i class="fa fa-check" aria-hidden="true"></i>
                  Check</a>
              </li>
              <li class="nav-item">
                <a href="{{ url_for('admin.event', event_id=event.id) }}"
                   title="Edit event details" class="nav-link">
                  <i class="fa fa-pencil" aria-hidden="true"></i>
                  Edit</a>
              </li>
              <li class="nav-item">
                <a href="{{ url_for('admin.project_new', event_id=event.id) }}"
                   title="Add a project here" class="nav-link">
                  <i class="fa fa-plus"></i>
                  Add</a>
              </li>
            {% endif %}
          {% endif %}
      {% else %}
        <li class="nav-item">
          <a class="nav-link nav-login"
             title="Sign in with your account"
             href="{{ url_for('auth.login') }}">
            <i class="fa fa-sign-in" aria-hidden="true"></i>
            Login
          </a>
        </li>
      {% endif %}

      <li class="nav-item">
        <a class="nav-link" id="navSearchButton"
           title="Search this dribdat site"
           href="{{ url_for('public.about') }}">
          <i class="fa fa-search" aria-hidden="true"></i>
          Search
        </a>
      </li>

    </ul>

  </div><!-- /.navbar-collapse -->
</nav>

<!-- Popup global alerts -->
<div id="global-notifications-alert" class="hidden">
  <div class="alert alert-info">
    <a class="close" title="Close" href="#">&times;</a>
    <i class="fa fa-info-circle float-left" aria-hidden="true"></i>
    <span id="notifications-status-text"></span>
  </div>
</div>

<!-- Popup search results -->
<div class="hidden container nav-search" id="navSearch"
     tabindex="-1" role="dialog" aria-labelledby="searchLabel" aria-hidden="true">
  <div class="profile-projects container-fluid mb-3">
    <div data-action="/api/project/search.json" id="search">
      <div class="content input-group">
        <div class="input-group-prepend">
          <span class="input-group-text">
            <i class="fa fa-search" aria-hidden="true"></i>
          </span>
        </div>
        <input type="text" class="form-control" name="q" aria-label="Search projects" placeholder="Start typing ..."  style="width:20em">
      </div>
    </div>
    <table class="table">
      <thead class="thead">
        <tr>
          <th scope="col">Team</th>
          <th scope="col">Event</th>
          <th scope="col">Updated</th>
        </tr>
      </thead>
      <tbody id="search-results"></tbody>
    </table>
    <div class="text-center mb-2" id="search-matches"></div>
  </div>
</div>

dribdat/templates/includes/pagination.html
<!-- Pagination widget -->
{% if data.pages > 1 %}
<div class="nav-pagination">
	{% if data.has_prev %}
		<a href="{{ url_for(endpoint, page=data.prev_num, sort=sort_by) }}" class="btn btn-secondary">&#9664;&nbsp; Previous</a>
	{% endif %}
	<span class="pagination m-3" style="display:inline-block">
	{%- for page in data.iter_pages() %}
		{% if page %}
			{% if page != data.page %}
				<a href="{{ url_for(endpoint, page=page, sort=sort_by) }}">{{ page }}</a>
			{% else %}
				<strong>{{ page }}</strong>
			{% endif %}
		{% else %}
			<span class="ellipsis">…</span>
		{% endif %}
	{%- endfor %}
	</span>
	{% if data.has_next %}
		<a href="{{ url_for(endpoint, page=data.next_num, sort=sort_by) }}" class="btn btn-secondary">Next &nbsp;&#9654;</a>
	{% endif %}
</div>
{% endif %}

dribdat/templates/includes/pleasewait.html
<div class="modal fade" id="pleasewaitModal" role="dialog" tabindex="-1">
  <div class="modal-dialog please-wait">
    <div class="modal-content">
      <div class="modal-header text-center"><h3>Please wait ...</h3></div>
      <div class="modal-body">The page should refresh in a few seconds 🏀</div>
    </div>
  </div>
</div><!-- /.modal -->