dribdat/user/forms.py
# -*- coding: utf-8 -*-
from flask_wtf import FlaskForm
from wtforms import PasswordField, StringField
from wtforms.validators import DataRequired, Email, EqualTo, Length

from .models import User


class RegisterForm(FlaskForm):
    """Register form."""

    username = StringField('Username',
                           validators=[DataRequired(), Length(min=3, max=25)])
    email = StringField('Email',
                        validators=[DataRequired(), Email(), Length(min=6, max=40)])
    password = PasswordField('Password',
                             validators=[DataRequired(), Length(min=6, max=40)])
    confirm = PasswordField('Verify password',
                            [DataRequired(), EqualTo('password', message='Passwords must match')])
    webpage_url = StringField(u'Online profile')

    def __init__(self, *args, **kwargs):
        """Create instance."""
        super(RegisterForm, self).__init__(*args, **kwargs)
        self.user = None

    def validate(self):
        """Validate the form."""
        initial_validation = super(RegisterForm, self).validate()
        if not initial_validation:
            return False
        user = User.query.filter_by(username=self.username.data).first()
        if user:
            self.username.errors.append('Username already registered')
            return False
        user = User.query.filter_by(email=self.email.data).first()
        if user:
            self.email.errors.append('Email already registered')
            return False
        return True

dribdat/__init__.py
"""Main application package."""

dribdat/admin/__init__.py
# -*- coding: utf-8 -*-

from . import views

dribdat/admin/views.py
# -*- coding: utf-8 -*-

from flask import Blueprint, render_template, redirect, url_for, make_response, request, flash, jsonify
from flask_login import login_required, current_user

from ..extensions import db, cache
from ..decorators import admin_required

from ..user.models import User, Event, Project, Category
from .forms import UserForm, EventForm, ProjectForm, CategoryForm

from datetime import datetime

from ..aggregation import GetProjectData

blueprint = Blueprint('admin', __name__, url_prefix='/admin')


@blueprint.route('/')
@login_required
@admin_required
def index():
    users = User.query.all()
    return render_template('admin/index.html', users=users, active='index')


@blueprint.route('/users')
@login_required
@admin_required
def users():
    users = User.query.all()
    return render_template('admin/users.html', users=users, active='users')


@blueprint.route('/user/<int:user_id>', methods=['GET', 'POST'])
@login_required
@admin_required
def user(user_id):
    user = User.query.filter_by(id=user_id).first_or_404()
    form = UserForm(obj=user, next=request.args.get('next'))

    if form.validate_on_submit():
        originalhash = user.password
        del form.id
        form.populate_obj(user)
        if form.password.data:
            user.set_password(form.password.data)
        else:
            user.password = originalhash
        db.session.add(user)
        db.session.commit()

        flash('User updated.', 'success')
        return users()

    return render_template('admin/user.html', user=user, form=form)

@blueprint.route('/user/new', methods=['GET', 'POST'])
@login_required
@admin_required
def user_new():
    user = User()
    form = UserForm(obj=user, next=request.args.get('next'))

    if form.validate_on_submit():
        del form.id
        form.populate_obj(user)

        db.session.add(user)
        db.session.commit()

        flash('User added.', 'success')
        return users()

    return render_template('admin/usernew.html', form=form)

@blueprint.route('/user/<int:user_id>/delete', methods=['GET', 'POST'])
@login_required
@admin_required
def user_delete(user_id):
    user = User.query.filter_by(id=user_id).first_or_404()
    if user.is_admin or user.active:
        flash('Admins and active users may not be deleted.', 'warning')
    elif len(user.projects) > 0:
        pl = ", ".join([str(i.name) for i in user.projects])
        flash('No users owning projects (%s) may be deleted.' % pl, 'warning')
    else:
        user.delete()
        flash('User deleted.', 'success')
    return users()

##############
##############
##############

@blueprint.route('/events')
@login_required
@admin_required
def events():
    events = Event.query.order_by(Event.starts_at.desc()).all()
    return render_template('admin/events.html', events=events, active='events')


@blueprint.route('/event/<int:event_id>', methods=['GET', 'POST'])
@login_required
@admin_required
def event(event_id):
    event = Event.query.filter_by(id=event_id).first_or_404()
    form = EventForm(obj=event, next=request.args.get('next'))

    if form.validate_on_submit():
        form.populate_obj(event)
        event.starts_at = datetime.combine(form.starts_date.data, form.starts_time.data)
        event.ends_at = datetime.combine(form.ends_date.data, form.ends_time.data)

        db.session.add(event)
        db.session.commit()

        cache.clear()

        flash('Event updated.', 'success')
        cache.clear()
        return events()

    form.starts_date.data = event.starts_at
    form.starts_time.data = event.starts_at
    form.ends_date.data = event.ends_at
    form.ends_time.data = event.ends_at
    return render_template('admin/event.html', event=event, form=form)

@blueprint.route('/event/new', methods=['GET', 'POST'])
@login_required
@admin_required
def event_new():
    event = Event()
    form = EventForm(obj=event, next=request.args.get('next'))

    if form.validate_on_submit():
        form.populate_obj(event)
        event.starts_at = datetime.combine(form.starts_date.data, form.starts_time.data)
        event.ends_at = datetime.combine(form.ends_date.data, form.ends_time.data)

        db.session.add(event)
        db.session.commit()

        flash('Event added.', 'success')
        cache.clear()
        return events()

    return render_template('admin/eventnew.html', form=form)

@blueprint.route('/event/<int:event_id>/delete', methods=['GET', 'POST'])
@login_required
@admin_required
def event_delete(event_id):
    event = Event.query.filter_by(id=event_id).first_or_404()
    if event.is_current:
        flash('Event must not be set as current in order to delete.', 'warning')
    elif len(event.categories) > 0:
        flash('No categories may be assigned to event in order to delete.', 'warning')
    elif len(event.projects) > 0:
        flash('No projects may be assigned to event in order to delete.', 'warning')
    else:
        event.delete()
        cache.clear()
        flash('Event deleted.', 'success')
    return events()

##############
##############
##############


@blueprint.route('/projects')
@login_required
@admin_required
def projects():
    # TODO: pagination...
    projects = Project.query.order_by(Project.updated_at.desc()).all()
    return render_template('admin/projects.html', projects=projects, active='projects')

@blueprint.route('/category/<int:category_id>/projects')
@login_required
@admin_required
def category_projects(category_id):
    category = Category.query.filter_by(id=category_id).first_or_404()
    projects = Project.query.filter_by(category_id=category_id).order_by(Project.id.desc())
    return render_template('admin/projects.html', projects=projects, category_name=category.name, active='projects')

@blueprint.route('/event/<int:event_id>/projects')
@login_required
@admin_required
def event_projects(event_id):
    event = Event.query.filter_by(id=event_id).first_or_404()
    projects = Project.query.filter_by(event_id=event_id).order_by(Project.id.desc())
    return render_template('admin/projects.html', projects=projects, event_name=event.name, active='projects')

@blueprint.route('/event/<int:event_id>/print')
@login_required
@admin_required
def event_print(event_id):
    now = datetime.utcnow().strftime("%d.%m.%Y %H:%M")
    event = Event.query.filter_by(id=event_id).first_or_404()
    projects = Project.query.filter_by(event_id=event_id, is_hidden=False)
    projects = projects.filter(Project.progress>0).order_by(Project.name)
    return render_template('admin/eventprint.html', event=event, projects=projects, curdate=now, active='projects')

@blueprint.route('/project/<int:project_id>', methods=['GET', 'POST'])
@login_required
@admin_required
def project_view(project_id):
    project = Project.query.filter_by(id=project_id).first_or_404()
    form = ProjectForm(obj=project, next=request.args.get('next'))
    form.user_id.choices = [(e.id, "%s" % (e.username)) for e in User.query.filter_by(active=True).order_by('username')]
    form.event_id.choices = [(e.id, e.name) for e in Event.query.order_by(Event.id.desc())]
    form.category_id.choices = [(c.id, c.name) for c in project.categories_all()]
    form.category_id.choices.insert(0, (-1, ''))
    if form.validate_on_submit():
        del form.id
        form.populate_obj(project)
        # Ensure project category remains blank
        if project.category_id == -1: project.category_id = None
        project.update()
        db.session.add(project)
        db.session.commit()
        flash('Project updated.', 'success')
        return projects()

    return render_template('admin/project.html', project=project, form=form)

@blueprint.route('/project/<int:project_id>/toggle', methods=['GET', 'POST'])
@login_required
@admin_required
def project_toggle(project_id):
    project = Project.query.filter_by(id=project_id).first_or_404()
    project.is_hidden = not project.is_hidden
    project.save()
    cache.clear()
    if project.is_hidden:
        flash('Project is now hidden.', 'success')
    else:
        flash('Project is now visible.', 'success')
    return project_view(project_id)

@blueprint.route('/project/<int:project_id>/delete', methods=['GET', 'POST'])
@login_required
@admin_required
def project_delete(project_id):
    project = Project.query.filter_by(id=project_id).first_or_404()
    if not project.is_hidden:
        flash('Project must be disabled.', 'warning')
    else:
        for a in project.activities: a.delete()
        project.delete()
        flash('Project deleted.', 'success')
    return projects()

@blueprint.route('/project/new', methods=['GET', 'POST'])
@login_required
@admin_required
def project_new():
    project = Project()
    form = ProjectForm(obj=project, next=request.args.get('next'))
    form.user_id.choices = [(e.id, "%s" % (e.username)) for e in User.query.filter_by(active=True).order_by('username')]
    form.event_id.choices = [(e.id, e.name) for e in Event.query.order_by(Event.id.desc())]
    form.category_id.choices = [(c.id, c.name) for c in project.categories_all()]
    form.category_id.choices.insert(0, (-1, ''))
    if form.validate_on_submit():
        del form.id
        form.populate_obj(project)
        project.update()
        db.session.add(project)
        db.session.commit()
        cache.clear()
        flash('Project added.', 'success')
        return projects()
    return render_template('admin/projectnew.html', form=form)

@blueprint.route('/project/<int:project_id>/autodata')
@login_required
@admin_required
def project_autodata(project_id):
    project = Project.query.filter_by(id=project_id).first_or_404()
    return jsonify(projectdata=GetProjectData(project.autotext_url))


##############
##############
##############

@blueprint.route('/categories')
@login_required
@admin_required
def categories():
    categories = Category.query.order_by(Category.event_id.desc()).all()

dribdat/app.py
# -*- coding: utf-8 -*-
"""The app module, containing the app factory function."""
from flask import Flask, render_template, redirect, url_for
from flask_cors import CORS

from dribdat import commands, public, user, admin
from dribdat.assets import assets
from dribdat.extensions import (
    hashing,
    cache,
    db,
    login_manager,
    migrate,
)
from dribdat.settings import ProdConfig
from dribdat.utils import timesince
from flask_misaka import Misaka
from flask_talisman import Talisman
from flask_dance.contrib.slack import make_slack_blueprint, slack

def init_app(config_object=ProdConfig):
    """An application factory, as explained here: http://flask.pocoo.org/docs/patterns/appfactories/.

    :param config_object: The configuration object to use.
    """
    app = Flask(__name__)
    app.config.from_object(config_object)

    cors = CORS(app, resources={r"/api/*": {"origins": "*"}})
    app.config['CORS_HEADERS'] = 'Content-Type'

    register_extensions(app)
    register_blueprints(app)
    register_oauthhandlers(app)
    register_errorhandlers(app)
    register_filters(app)
    register_loggers(app)
    register_shellcontext(app)
    register_commands(app)
    return app


def register_extensions(app):
    """Register Flask extensions."""
    assets.init_app(app)
    hashing.init_app(app)
    cache.init_app(app)
    db.init_app(app)
    login_manager.init_app(app)
    migrate.init_app(app, db)
    if 'SERVER_SSL' in app.config and app.config['SERVER_SSL']:
        Talisman(app)
    return None


def register_blueprints(app):
    """Register Flask blueprints."""
    app.register_blueprint(public.views.blueprint)
    app.register_blueprint(public.auth.blueprint)
    app.register_blueprint(public.api.blueprint)
    app.register_blueprint(user.views.blueprint)
    app.register_blueprint(admin.views.blueprint)
    return None

def register_oauthhandlers(app):
    if app.config["OAUTH_TYPE"]:
        if app.config["OAUTH_TYPE"] == 'slack':
            blueprint = make_slack_blueprint(
                client_id=app.config["OAUTH_ID"],
                client_secret=app.config["OAUTH_SECRET"],
                subdomain=app.config["OAUTH_DOMAIN"],
                scope="identity.basic,identity.email",
                redirect_to="auth.slack_login",
                login_url="/login",
                # authorized_url=None,
                # session_class=None,
                # storage=None,
            )
            app.register_blueprint(blueprint, url_prefix="/oauth")

def register_errorhandlers(app):
    """Register error handlers."""
    def render_error(error):
        """Render error template."""
        # If a HTTPException, pull the `code` attribute; default to 500
        error_code = getattr(error, 'code', 500)
        return render_template('{0}.html'.format(error_code)), error_code
    for errcode in [401, 404, 500]:
        app.errorhandler(errcode)(render_error)
    return None


def register_shellcontext(app):
    """Register shell context objects."""
    def shell_context():
        """Shell context objects."""
        return {
            'db': db,
            'User': user.models.User}

    app.shell_context_processor(shell_context)


def register_commands(app):
    """Register Click commands."""
    app.cli.add_command(commands.test)
    app.cli.add_command(commands.lint)
    app.cli.add_command(commands.clean)
    app.cli.add_command(commands.urls)


def register_filters(app):
    Misaka(app, autolink=True, fenced_code=True, strikethrough=True, tables=True)
    @app.template_filter()
    def since_date(value):
        return timesince(value)
    @app.template_filter()
    def until_date(value):
        return timesince(value, default="now!", until=True)
    @app.template_filter()
    def format_date(value, format='%d.%m.%Y'):
        return value.strftime(format)
    @app.template_filter()
    def format_datetime(value, format='%d.%m.%Y %H:%M'):
        return value.strftime(format)


def register_loggers(app):
    # if os.environ.get('HEROKU') is not None:
        # app.logger.info('hello Heroku!')
    import logging
    stream_handler = logging.StreamHandler()
    app.logger.addHandler(stream_handler)
    app.logger.setLevel(logging.INFO)

dribdat/user/__init__.py
# -*- coding: utf-8 -*-
"""The user module."""
from . import views, validators  # noqa

from .constants import (
    USER_ROLE, ADMIN, USER, USER_STATUS, ACTIVE,
    PROJECT_PROGRESS, PROJECT_PROGRESS_PHASE,
    projectProgressList
)

dribdat/user/views.py
# -*- coding: utf-8 -*-
"""User views."""
from flask import Blueprint, render_template
from flask_login import login_required

blueprint = Blueprint('user', __name__, url_prefix='/users', static_folder='../static')


@blueprint.route('/')
@login_required
def members():
    """List members."""
    return render_template('users/members.html')

dribdat/templates/includes/analytics.html
{% if config.ANALYTICS_FATHOM %}
<!-- Fathom - beautiful, simple website analytics -->
    {% if config.ANALYTICS_FATHOM_SITE %}
    <script src="https://{{ config.ANALYTICS_FATHOM_SITE }}/script.js" site="{{ config.ANALYTICS_FATHOM }}" async defer></script>
    {% else %}
    <script src="https://cdn.usefathom.com/script.js" site="{{ config.ANALYTICS_FATHOM }}" async defer></script>
    {% endif %}
<!-- / Fathom -->
{% endif %}

{% if config.ANALYTICS_SIMPLE %}
<!-- Simple Analytics - Simple, clean, privacy-friendly analytics -->
<script async defer src="https://scripts.simpleanalyticscdn.com/latest.js"></script>
<noscript><img src="https://queue.simpleanalyticscdn.com/noscript.gif" alt=""
/></noscript>
{% endif %}

{% if config.ANALYTICS_GOOGLE %}
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id={{ config.ANALYTICS_GOOGLE }}"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());
  gtag('config', '{{ config.ANALYTICS_GOOGLE }}');
</script>
<!-- / Google Analytics -->
{% endif %}

dribdat/templates/includes/footer.html
<footer>
  <small>
    <ul class="footer-nav">
      <li>Open source under the MIT license.</li>
      <li>
        <b><a href="{{ url_for('public.about') }}">About
          <small>D R I
          <i class="fa fa-thumbs-up"></i>
          <i style="-moz-transform: scale(-1, 1); -webkit-transform: scale(-1, 1); -o-transform: scale(-1, 1); -ms-transform: scale(-1, 1); transform: scale(-1, 1);" class="fa fa-thumbs-up"></i>
          A T</small></a></b>
      </li><li>
        <a href="https://github.com/datalets/dribdat/issues">Issues</a>
      </li>
      {% if config.ANALYTICS_HREF %}
      <li>
        <a href="{{ config.ANALYTICS_HREF }}">Analytics</a>
      </li>
      {% endif %}
    </ul>
  </small>
</footer>

dribdat/templates/includes/nav.html
<nav class="navbar navbar-expand-lg navbar-light bg-faded" role="navigation">

  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbar-main-collapse" aria-controls="navbar-main-collapse" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <a class="navbar-brand" href="{{ url_for('public.home') }}">
      <i style="-moz-transform: scale(1, 1); -webkit-transform: scale(1, 1); -o-transform: scale(1, 1); -ms-transform: scale(1, 1); transform: scale(1, 1);" class="fa fa-thumbs-up"></i>
      <i style="-moz-transform: scale(-1, 1); -webkit-transform: scale(-1, 1); -o-transform: scale(-1, 1); -ms-transform: scale(-1, 1); transform: scale(-1, 1);" class="fa fa-thumbs-up"></i>
    </a>
  </div>

  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse" id="navbar-main-collapse">
    <ul class="navbar-nav navbar-left mr-auto">
      {% if event %}
        <li class="nav-item">
          <a href="{{ url_for('public.event', event_id=event.id) }}#top">
            {% if event.has_finished %}
              <i class="fa fa-bars" aria-hidden="true"></i>
              Results
            {% elif event.has_started %}
              <i class="fa fa-bars" aria-hidden="true"></i>
              Projects
            {% else %}
              <i class="fa fa-trophy" aria-hidden="true"></i>
              Challenges
            {% endif %}
          </a>
        </li>
        {% if event.resources %}
        <li class="nav-item">
          <a href="{{ url_for('public.event', event_id=event.id) }}#resources">
            <i class="fa fa-cart-plus" aria-hidden="true"></i>
            Resources
          </a>
        </li>
        {% endif %}
        {% if event.can_start_project %}
        <li class="nav-item">
          <a href="{{ url_for('public.project_new', event_id=event.id) }}">
            <i class="fa fa-rocket"></i>
            Get started
          </a>
        </li>
        {% endif %}
        {% if event.community_url %}
        <li class="nav-item">
          <a href="{{ event.community_url }}">
            <i class="fa fa-comment"></i>
            Community
          </a>
        </li>
        {% endif %}
      {% endif %}

      {% if tabs %}
        {% for tab, link in tabs %}
        <li class="nav-item" class="{% if active == tab %}active{% endif %}">
          <a href="{{ link }}">{{ tab|capitalize }}</a>
        </li>
        {% endfor %}
      {% endif %}

      {% if current_user and current_user.is_authenticated %}
          <li class="nav-item">
            <a class="navbar-link" href="{{ url_for('auth.user_profile') }}">
              <i class="fa fa-child"></i>
              Profile
              <b>{{ current_user.username }}</b>
            </a>
          </li>
          {% if current_user.is_admin %}
            <li class="nav-item">
              <a class="navbar-link" href="{{ url_for('admin.index') }}">
                <i class="fa fa-gear"></i>
                Admin
              </a>
            </li>
          {% endif %}
          <li class="nav-item">
            <a class="navbar-link" href="{{ url_for('auth.logout') }}">
              <i class="fa fa-sign-out"></i>
              Logout
            </a>
          </li>
      {% else %}
        <li class="nav-item"><a href="{{ url_for('auth.login') }}">Log in<i class="fa fa-sign-in"></i></a></li>
        {% if not config.DRIBDAT_NOT_REGISTER %}
          <li class="nav-item">
            <a href="{{ url_for('auth.register') }}">
              <i class="fa fa-child"></i>
              Create account
            </a></li>
        {% endif %}
      {% endif %}
    </ul>
  </div><!-- /.navbar-collapse -->

</nav>

{% if event %}
<div class="container event-header">
  <div class="section section-centered section-header">
    <a href="{{ url_for('public.event', event_id=event.id) }}#top">
    {% if event.logo_url %}
      <div class="section-header-logo">
        <img id="event-logo" src="{{ event.logo_url }}" alt="{{ event.hostname }}">
      </div>
    {% endif %}
    <div class="section-header-content">
      <h3>{{ event.name }}</h3>
      <h4>{{ event.date }}<br>{{ event.location }}</h4>
    </a>
    </div>
  </div>
</div>
<style type="text/css">{{ event.custom_css }}</style>
{% endif %}

dribdat/templates/includes/quickstart.html
<p>When documenting an idea or project, you can use <a href="https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet" target="_blank">Markdown formatting</a> in the <b>Description</b> or connect to your README in a supported open source community site: <a href="https://github.com" target="_blank">GitHub</a>, <a href="https://gitlab.com" target="_blank">GitLab</a>, <a href="https://bitbucket.org" target="_blank">Bitbucket</a>, <a href="http://etherpad.org" target="_blank">Etherpad Lite</a>, Google Docs (<i>Publish to Web</i>) and <a href="http://make.opendata.ch/wiki/project:home" target="_blank">DokuWiki</a>. You will then find a <a href="#" class="btn btn-warning disabled btn-sm">Sync</a> button on your project page for quickly pulling in changes.</p>

<p>After creating a project, you can customise the icon, color and image, and your team status. By updating your <b>Progress</b>, you can communicate how far along you are in development. Your team members can click the <a href="#" class="btn btn-primary disabled btn-sm">Join</a> button at the top of your project page to link their profile and make changes.</p>

<p><i>Need more help? Get in touch with the organising team using the <b>Community</b> links, or raise a <a href="https://github.com/datalets/dribdat/issues" target="_blank">GitHub issue</a>.</i></p>

dribdat/templates/includes/reset_password.html
<p>Forgot your password, {{ username }}?</p>

<p>{{ project }} received a request to reset the password for your {{ project }} account {{ username }}.</p>

<p>If you want to reset your password, click on the link below (or copy and paste the URL into your browser):</p>

<a href="{{ url }}">Click to Reset Password</a>

<p>This link takes you to a secure page where you can change your password. For tips on selecting a strong password, see our Safe Tweeting help page.</p>

<p>If you don't want to reset your password, please ignore this message. Your password will not be reset. If you have any concerns, please contact us at {{ project }} Support.</p>

<p>The {{ project }} Team</p>